### ISSUE TITLE
No Changelog found

### ISSUE THREAD

**Issue by davetcoleman** [rosindex/rosindex.github.io#63] opened 2015-01-19 18:48 UTC
Me repo has a changelog here: https://github.com/davetcoleman/moveit_visual_tools/blob/indigo-devel/CHANGELOG.rst

But it says none found:
![screen shot 2015-01-19 at 11 48 25 am](https://cloud.githubusercontent.com/assets/561060/5805939/245d3e98-9fd1-11e4-9b3e-bc9abb7a3bd6.png)

**Comment by davetcoleman** [comment] 2015-01-19 18:49
Possible duplicate https://github.com/rosindex/rosindex.github.io/issues/58

**Comment by jbohren** [comment] 2015-01-19 19:33
Yeah, duplicate of #58 it's just not scraping them yet.

**Closed by jbohren** 2015-01-19 19:33 UTC
